In [1]:
import distance_funcs
import numpy as np
from os import chdir
from sklearn.metrics.pairwise import cosine_similarity as sklearn_cosine_similarity

In [2]:
chdir("c:/Users/Raya/OneDrive/Documents/3-CSAI/CSAI-Y3-S2/Thesis/Replication")

In [4]:
TOY_VECTS = np.array([np.array(([1.0,-2.0,3.0])), np.array(([-4.0,5.0,6.0])), np.array(([7.0,8.0,-9.0]))])
TOY_WORDS = ['cup', 'cat', 'dog']

In [9]:
data = np.load("data/sample_word_vects.npz", allow_pickle=True)
ids = data['ids']
words = data['words']
vectors = data['vectors']

print(f"First 10 ids: {ids[:10]}")
print(f"First 10 words: {words[:10]}")
print(f"First 10 vectors:\n{vectors[:10]}")
print(f"vectors is a {type(vectors)}")
print(f"vectors shape: {vectors.shape}")

First 10 ids: [3576 4501 3327 1102 1650  240 5480 4211 4321 6761]
First 10 words: ['league' 'album' 'game' 'party' 'women' 'church' 'song' 'station' 'town'
 'president']
First 10 vectors:
[[ 1.13337643e-01  1.40484904e-01  3.74122065e-01 ...  2.33168057e-03
  -7.16891078e-03 -8.52921721e-03]
 [ 1.50450789e-01 -4.31291522e-01  8.04129079e-03 ... -9.17724888e-03
   2.34008918e-03 -1.49247768e-03]
 [ 7.16353961e-02  2.09700719e-02  1.00467108e-01 ...  5.39575412e-03
  -3.49315731e-05 -2.24411586e-03]
 ...
 [ 9.01282158e-02  5.79194661e-02 -1.28253646e-01 ...  1.16877488e-02
   1.31945628e-02 -2.23398991e-03]
 [ 6.85584396e-02  6.90132216e-02 -6.92020170e-02 ...  4.36430862e-03
   3.91536325e-03 -7.95992962e-03]
 [ 5.07194125e-02  2.83445260e-02 -1.18512292e-02 ... -2.41039906e-04
   6.70018938e-03 -6.51316655e-04]]
vectors is a <class 'numpy.ndarray'>
vectors shape: (100, 500)


In [10]:
# Sample the first 4 vectors and print the words they encode

vects = vectors[:4]
print(type(vects[0]))
print(f"Sample of 4 vectors we will test on:\n{vects}")

print(f"Words: {words[:4]}")

<class 'numpy.ndarray'>
Sample of 4 vectors we will test on:
[[ 1.13337643e-01  1.40484904e-01  3.74122065e-01 ...  2.33168057e-03
  -7.16891078e-03 -8.52921721e-03]
 [ 1.50450789e-01 -4.31291522e-01  8.04129079e-03 ... -9.17724888e-03
   2.34008918e-03 -1.49247768e-03]
 [ 7.16353961e-02  2.09700719e-02  1.00467108e-01 ...  5.39575412e-03
  -3.49315731e-05 -2.24411586e-03]
 [ 6.90431803e-02  4.47305974e-02 -3.26518431e-02 ...  3.23385872e-03
  -2.32367157e-03  7.55563937e-03]]
Words: ['league' 'album' 'game' 'party']


In [5]:
# Reference: cosine similarities using sklearn's function
sk_cos_sim = sklearn_cosine_similarity(vects)
print(sk_cos_sim)

print(f"Values range from -1 to 1: {distance_funcs.check_value_range(sk_cos_sim, -1, 1)}")

[[ 1.00000000e+00  1.06149259e-03  1.47369851e-03 -6.10924970e-03]
 [ 1.06149259e-03  1.00000000e+00 -3.92126062e-03  2.43641758e-04]
 [ 1.47369851e-03 -3.92126062e-03  1.00000000e+00  2.38907739e-03]
 [-6.10924970e-03  2.43641758e-04  2.38907739e-03  1.00000000e+00]]
Min: -0.006109249695510285
Max: 1.0000000000000004
Values range from -1 to 1: False


In [6]:
cos_sim_matrix = distance_funcs.cosine_similarities_matrix(vects)
print(cos_sim_matrix)

print(cos_sim_matrix.shape)

print(f"Values range from -1 to 1: {distance_funcs.check_value_range(cos_sim_matrix, -1, 1)}")

[[ 1.0000000e+00  1.0614926e-03  1.4736985e-03 -6.1092497e-03]
 [ 1.0614926e-03  1.0000000e+00 -3.9212606e-03  2.4364180e-04]
 [ 1.4736985e-03 -3.9212606e-03  1.0000000e+00  2.3890774e-03]
 [-6.1092497e-03  2.4364180e-04  2.3890774e-03  1.0000000e+00]]
(4, 4)
Min: -0.0061092497
Max: 1.0
Values range from -1 to 1: True


In [7]:
cos_dist_matrix_basic = distance_funcs.cosine_distances_matrix(vects)

print(cos_dist_matrix_basic)
print(f"Values range from 0 to 2: {distance_funcs.check_value_range(cos_dist_matrix_basic, 0, 2)}")

[[0.         0.99893851 0.9985263  1.00610925]
 [0.99893851 0.         1.00392126 0.99975636]
 [0.9985263  1.00392126 0.         0.99761092]
 [1.00610925 0.99975636 0.99761092 0.        ]]
Min: 0.0
Max: 1.0061092497
Values range from 0 to 2: True


In [8]:
cos_dist_matrix_map = distance_funcs.cosine_distances_matrix(vects, rescaling='norm_cos_sim')

print(cos_dist_matrix_map)
print(f"Values range from 0 to 1: {distance_funcs.check_value_range(cos_dist_matrix_map, 0, 1)}")

[[0.         0.49946925 0.49926315 0.50305462]
 [0.49946925 0.         0.50196063 0.49987818]
 [0.49926315 0.50196063 0.         0.49880546]
 [0.50305462 0.49987818 0.49880546 0.        ]]
Min: 0.0
Max: 0.5030546248500001
Values range from 0 to 1: True


In [9]:
cos_dist_matrix_ang = distance_funcs.cosine_distances_matrix(vects, rescaling='angular_dist')

print(cos_dist_matrix_ang)
print(f"Values range from 0 to 1: {distance_funcs.check_value_range(cos_dist_matrix_ang, 0, 1)}")

[[0.         0.49966212 0.49953091 0.50194465]
 [0.49966212 0.         0.50124818 0.49992245]
 [0.49953091 0.50124818 0.         0.49923953]
 [0.50194465 0.49992245 0.49923953 0.        ]]
Min: 0.0
Max: 0.5019446466734558
Values range from 0 to 1: True


In [10]:
avg_cos_dist_basic = distance_funcs.average_distances(cos_dist_matrix_basic)
print(avg_cos_dist_basic) # Note: range is [0-2], so values >1 are normal

avg_cos_dist_map = distance_funcs.average_distances(cos_dist_matrix_map)
print(avg_cos_dist_map)

avg_cos_dist_ang = distance_funcs.average_distances(cos_dist_matrix_ang)
print(avg_cos_dist_ang)

[1.00119135 1.00087204 1.00001949 1.00115884]
[0.50059568 0.50043602 0.50000975 0.50057942]
[0.50037922 0.50027758 0.50000621 0.50036888]


In [3]:
# Testing cos sim and dist functions on toy arrays

vecs = np.array([np.array(([1.0,-2.0,3.0])), np.array(([-4.0,5.0,6.0])), np.array(([7.0,8.0,-9.0]))])
print(f"`vecs` is a: {type(vecs)}")
print(f"It looks like this:\n{vecs}")
for i, v in enumerate(vecs):
    print(f"Vector {i} is: {v}")

print()
cos_sim_mx = distance_funcs.cosine_similarities_matrix(vecs)
print(f"Cosine similarity matrix:\n{cos_sim_mx}\n")

cos_dist_mx_raw = distance_funcs.cosine_distances_matrix(vecs, rescaling=None)
print(f"Cosine distances raw:\n{cos_dist_mx_raw}\n")

cos_dist_mx_abs = distance_funcs.cosine_distances_matrix(vecs, rescaling='abs_cos_sim')
print(f"Cosine distances 'abs_cos_sim':\n{cos_dist_mx_abs}\n")

cos_dist_mx_norm = distance_funcs.cosine_distances_matrix(vecs, rescaling='norm_cos_sim')
print(f"Cosine distances 'norm_cos_sim':\n{cos_dist_mx_norm}\n")

cos_dist_mx_ang = distance_funcs.cosine_distances_matrix(vecs, rescaling='angular_dist')
print(f"Cosine distances 'angular_dist':\n{cos_dist_mx_ang}\n")

`vecs` is a: <class 'numpy.ndarray'>
It looks like this:
[[ 1. -2.  3.]
 [-4.  5.  6.]
 [ 7.  8. -9.]]
Vector 0 is: [ 1. -2.  3.]
Vector 1 is: [-4.  5.  6.]
Vector 2 is: [ 7.  8. -9.]

Cosine similarity matrix:
[[ 1.          0.12182898 -0.6907766 ]
 [ 0.12182898  1.         -0.34363949]
 [-0.6907766  -0.34363949  1.        ]]

Cosine distances raw:
[[0.         0.87817102 1.6907766 ]
 [0.87817102 0.         1.34363949]
 [1.6907766  1.34363949 0.        ]]

Cosine distances 'abs_cos_sim':
[[0.         0.87817102 0.3092234 ]
 [0.87817102 0.         0.65636051]
 [0.3092234  0.65636051 0.        ]]

Cosine distances 'norm_cos_sim':
[[0.         0.43908551 0.8453883 ]
 [0.43908551 0.         0.67181974]
 [0.8453883  0.67181974 0.        ]]

Cosine distances 'angular_dist':
[[0.         0.46112406 0.74273119]
 [0.46112406 0.         0.61165982]
 [0.74273119 0.61165982 0.        ]]



In [6]:
# Testing function for edit distance matrix on toy example

words_diff_length = ['apple', 'banana', 'pear']
words_same_length = ['cup', 'cat', 'dog']

edit_dist_mx_diff_length_sym = distance_funcs.edit_distances_matrix(words_diff_length, symmetric=True)
print(f"Edit distances for list of words of different lengths (symmetric=True):\n{edit_dist_mx_diff_length_sym}")
print(f"Symmetric: {distance_funcs.is_symmetric(edit_dist_mx_diff_length_sym)}\n")

edit_dist_mx_diff_length_non_sym = distance_funcs.edit_distances_matrix(words_diff_length, symmetric=False)
print(f"Edit distances for list of words of different lengths (symmetric=False):\n{edit_dist_mx_diff_length_non_sym}")
print(f"Symmetric: {distance_funcs.is_symmetric(edit_dist_mx_diff_length_non_sym)}\n")


edit_dist_mx_same_length_sym = distance_funcs.edit_distances_matrix(words_same_length, symmetric=True)
print(f"Edit distances for list of words of same length (symmetric=True):\n{edit_dist_mx_same_length_sym}")
print(f"Symmetric: {distance_funcs.is_symmetric(edit_dist_mx_same_length_sym)}\n")

edit_dist_mx_same_length_non_sym = distance_funcs.edit_distances_matrix(words_same_length, symmetric=False)
print(f"Edit distances for list of words of same length (symmetric=False):\n{edit_dist_mx_same_length_non_sym}")
print(f"Symmetric: {distance_funcs.is_symmetric(edit_dist_mx_same_length_non_sym)}")

# NOTE: since all edit costs are equal, all matrices are symmetric

Edit distances for list of words of different lengths (symmetric=True):
[[0. 5. 4.]
 [5. 0. 5.]
 [4. 5. 0.]]
Symmetric: True

Edit distances for list of words of different lengths (symmetric=False):
[[0. 5. 4.]
 [5. 0. 5.]
 [4. 5. 0.]]
Symmetric: True

Edit distances for list of words of same length (symmetric=True):
[[0. 2. 3.]
 [2. 0. 3.]
 [3. 3. 0.]]
Symmetric: True

Edit distances for list of words of same length (symmetric=False):
[[0. 2. 3.]
 [2. 0. 3.]
 [3. 3. 0.]]
Symmetric: True


In [11]:
# Test distances computation scripts

# Define rescaling options for cosine distance
rescaling_options = {
    'none': None,
    'abs': 'abs_cos_sim',
    'norm': 'norm_cos_sim',
    'ang': 'angular_dist'
}

# --------------- Computing distances ---------------
for rescaling, rescaling_string in rescaling_options.items():
    print(f"--- Rescaling: {rescaling} ---")
    # Fetch LSA vectors for the words in the vocabulary of the current length
    vects = TOY_VECTS
    
    # Compute cosine distances
    cosine_distances = distance_funcs.cosine_distances_matrix(vects, rescaling=rescaling_string)
    print(f"Cosine distances:\n{cosine_distances}\n")
        
    words = TOY_WORDS
    edit_distances = distance_funcs.edit_distances_matrix(words)
    print(f"Edit distances:\n{edit_distances}\n")

--- Rescaling: none ---
Cosine distances:
[[0.         0.87817102 1.6907766 ]
 [0.87817102 0.         1.34363949]
 [1.6907766  1.34363949 0.        ]]

Edit distances:
[[0. 2. 3.]
 [2. 0. 3.]
 [3. 3. 0.]]

--- Rescaling: abs ---
Cosine distances:
[[0.         0.87817102 0.3092234 ]
 [0.87817102 0.         0.65636051]
 [0.3092234  0.65636051 0.        ]]

Edit distances:
[[0. 2. 3.]
 [2. 0. 3.]
 [3. 3. 0.]]

--- Rescaling: norm ---
Cosine distances:
[[0.         0.43908551 0.8453883 ]
 [0.43908551 0.         0.67181974]
 [0.8453883  0.67181974 0.        ]]

Edit distances:
[[0. 2. 3.]
 [2. 0. 3.]
 [3. 3. 0.]]

--- Rescaling: ang ---
Cosine distances:
[[0.         0.46112406 0.74273119]
 [0.46112406 0.         0.61165982]
 [0.74273119 0.61165982 0.        ]]

Edit distances:
[[0. 2. 3.]
 [2. 0. 3.]
 [3. 3. 0.]]



In [13]:
def compute_gls(X, Y, gamma_func, alphabet):
    """
    Compute the Generalized Levenshtein Similarity (GLS) between two strings X and Y.

    Parameters:
        X, Y: str
            The strings between which the GLS is to be computed.
        gamma_func: function
            A function that takes two characters as input and returns the cost of transforming
            one character into another.
        alphabet: list or set
            The alphabet from which the characters are drawn.

    Returns:
        float
            The computed Generalized Levenshtein Similarity between X and Y.
    """
    # Compute alpha using the provided gamma function and alphabet
    alpha = compute_alpha(gamma_func, alphabet)

    # Compute Generalized Levenshtein Distance between X and Y
    gld = gls(X, Y, gamma_func)

    # Calculate GLS using the formula
    gls = (alpha * (len(X) + len(Y)) - gld) / 2

    return gls

5

In [14]:
import numpy as np

def cost_func(X, Y):
    return 1

def generalized_levenshtein_distance(source, target, cost_func=cost_func):
    """
    Compute Generalized Levenshtein Distance (GLD) between two strings.
    
    Parameters:
        X, Y (str): The strings between which the GLD is to be computed.
        cost_func (func): A function that takes two characters as input and returns the cost of transforming
            one character into another.

    Returns:
        int: The computed Generalized Levenshtein Distance between X and Y.
    """    
    n, m = len(source), len(target)
    dist_matrix = np.zeros((n+1, m+1), dtype=int)
    
    if costs == None:
        costs = {'deletion': 1, 'insertion': 1, 'substitution': 1}
    
    # Initialize the matrix: the zeroth row and column is the distance from the empty string
    dist_matrix[0][0] = 0
    for i in range(1, n+1):
        dist_matrix[i][0] = dist_matrix[i-1][0] + 1 # deletion
    for j in range(1, m+1):
        dist_matrix[0][j] = dist_matrix[0][j-1] + 1 # insertion
    
    # Dynamic programming
    for i in range(1, n+1):
        for j in range(1, m+1):
            if source[i-1] == target[j-1]:
                dist_matrix[i][j] = dist_matrix[i-1][j-1]
            else:
                dist_matrix[i][j] = min(dist_matrix[i-1][j] + costs['deletion'], # deletion
                                        dist_matrix[i][j-1] + costs['insertion'], # insertion
                                        dist_matrix[i-1][j-1] + costs['substitution']) # substitution
    
    return int(dist_matrix[n][m])


def compute_alpha(gamma_func, alphabet):
    """
    Compute the value of alpha for a given alphabet and gamma function.

    Parameters:
        gamma_func: function
            A function that takes two characters as input and returns the cost of transforming
            one character into another.
        alphabet: list or set
            The alphabet from which the characters are drawn.

    Returns:
        float
            The computed value of alpha.
    """
    max_gamma_insert = max(gamma_func(a, '\0') for a in alphabet)
    max_gamma_delete = max(gamma_func('\0', b) for b in alphabet)
    max_char = max(alphabet)
    
    return max(max_gamma_insert, max_gamma_delete, max_char)


source = 'mast'
target = 'ports'
print(generalized_levenshtein_distance(source, target))

4
